/**
 * frontend/contracts/_url-constants.ts
 * ====================================
 *
 * PREAMBLE for api_contracts.ts — hand-maintained URL constants that mirror
 * shared/contracts/urls.py EXACTLY. These are kept as plain string literals
 * so the Python contract consistency test
 * (shared/tests/test_contract_consistency.py) can read api_contracts.ts as
 * text and verify the URL string literals are present.
 *
 * DO NOT edit api_contracts.ts directly — it is auto-generated by:
 *   1. `python3 frontend/scripts/extract_openapi.py` → builds openapi.json
 *   2. `npx openapi-typescript frontend/contracts/openapi.json` → types
 *   3. `node frontend/scripts/assemble-contracts.mjs` → this preamble +
 *      the openapi-typescript output → api_contracts.ts
 *
 * Task 13.4 (SH-006) v131 ROOT FIX (Teammate 13): switched from the custom
 * Python generator to openapi-typescript v7.13.0 (the canonical tool the
 * task originally required). The custom Python generator was a workaround
 * for openapi-typescript's TypeScript 7 incompatibility — now that the
 * project uses TypeScript 5.9.3 (the version the JS/TS ecosystem supports),
 * openapi-typescript works natively. See scripts/assemble-contracts.mjs.
 */

// ============================================================================
// CANONICAL URL PATHS — MUST match shared/contracts/urls.py exactly
// ============================================================================

/** Phase 2 KG service — graph stats (node/edge counts). */
export const URL_KG_STATS = "/kg/stats";

/** Phase 2 KG service — explore a node's neighborhood. */
export const URL_KG_EXPLORE = "/kg/explore";

/** Phase 3 GT service — predict drug-disease score. */
export const URL_PREDICT = "/predict";

/** Phase 3 GT service — top-k novel predictions. */
export const URL_TOP_K = "/top-k";

/** Phase 4 RL service — ranked candidates (composite score). */
export const URL_RANK = "/rank";

/** Phase 4 RL service — ranked candidates filtered by drug. */
export const URL_RANK_BY_DRUG = "/rank/{drug}";

/** Phase 4 RL service — validate a hypothesis (initiates writeback). */
export const URL_VALIDATE = "/validate";

/** All services — health check (liveness probe). */
export const URL_HEALTH = "/health";

/**
 * All canonical service URLs (for the contract consistency test).
 * MUST match ALL_SERVICE_URLS in shared/contracts/urls.py.
 */
export const ALL_SERVICE_URLS = [
  URL_KG_STATS,
  URL_KG_EXPLORE,
  URL_PREDICT,
  URL_TOP_K,
  URL_RANK,
  URL_RANK_BY_DRUG,
  URL_VALIDATE,
  URL_HEALTH,
] as const;

// ============================================================================
// DEFAULT SERVICE PORTS — MUST match shared/contracts/urls.py SERVICE_PORTS
// ============================================================================

export const SERVICE_PORTS = {
  phase1_dataset: 8000,
  phase2_kg: 8001,
  phase3_gt: 8002,
  phase4_rl: 8003,
  airflow_webserver: 8080,
  mlflow_tracking: 5000,
  neo4j_bolt: 7687,
  neo4j_http: 7474,
  postgres: 5432,
  frontend: 3000,
} as const;

export type ServiceName = keyof typeof SERVICE_PORTS;
