/**
 * frontend/contracts/api_contracts.ts
 * ===================================
 *
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * This file is regenerated from the four Python FastAPI services' OpenAPI
 * schemas by:
 *
 *     python3 frontend/scripts/extract_openapi.py   # builds openapi.json
 *     python3 frontend/scripts/generate_api_contracts.py
 *         # ↑ this file — converts openapi.json → api_contracts.ts
 *
 * Task 13.4 (SH-006) ROOT FIX (Teammate 13, v129):
 *   The previous file was 606 lines of hand-written TypeScript with
 *   interfaces that DIVERGED from what the Python services actually
 *   returned (the audit flagged phantom fields that Python never emitted).
 *   This file is now generated from the source of truth — the FastAPI
 *   apps' own ``app.openapi()`` output. Any change to a Python endpoint's
 *   URL, request body, or response shape is now a 2-file change: the
 *   Python service + this regenerated file. The CI check
 *   (``npm run check:contracts``) fails if the file is out of date.
 *
 * Why not use ``openapi-typescript`` (the npm package)?
 *   The upstream package requires TypeScript 5 (its ``ts.factory`` API
 *   was removed in TypeScript 7, which this project uses). When the
 *   upstream package adds TypeScript 7 support, this script can be
 *   replaced with:
 *       npx openapi-typescript frontend/contracts/openapi.json \
 *           -o frontend/contracts/api_contracts.ts
 *   The output structure of this script matches openapi-typescript v7's
 *   output (``paths``, ``components``, ``operations`` interfaces) so the
 *   swap will be transparent to consumers.
 *
 * Coexistence with the hand-written URL constants below:
 *   The hand-written ``URL_KG_STATS`` etc. constants at the top of this
 *   file are kept for backwards compatibility with the Python contract
 *   consistency test (shared/tests/test_contract_consistency.py), which
 *   reads this file as text and verifies the URL string literals are
 *   present. They mirror shared/contracts/urls.py exactly. If you change
 *   a URL, change it in shared/contracts/urls.py AND regenerate this file.
 *
 * Generation timestamp: 2026-07-20 04:45:44 UTC
 * OpenAPI schema source: frontend/contracts/openapi.json
 */

// ============================================================================
// CANONICAL URL PATHS — MUST match shared/contracts/urls.py exactly
// ============================================================================
// These constants are kept as plain string literals so the Python contract
// consistency test can read this file as text and verify the URLs match.
// They are NOT generated from OpenAPI — they are the canonical source that
// the Python services import from shared/contracts/urls.py.

/** Phase 2 KG service — graph stats (node/edge counts). */
export const URL_KG_STATS = "/kg/stats";

/** Phase 2 KG service — explore a node's neighborhood. */
export const URL_KG_EXPLORE = "/kg/explore";

/** Phase 3 GT service — predict drug-disease score. */
export const URL_PREDICT = "/predict";

/** Phase 3 GT service — top-k novel predictions. */
export const URL_TOP_K = "/top-k";

/** Phase 4 RL service — ranked candidates (composite score). */
export const URL_RANK = "/rank";

/** Phase 4 RL service — ranked candidates filtered by drug. */
export const URL_RANK_BY_DRUG = "/rank/{drug}";

/** Phase 4 RL service — validate a hypothesis (initiates writeback). */
export const URL_VALIDATE = "/validate";

/** All services — health check (liveness probe). */
export const URL_HEALTH = "/health";

/**
 * All canonical service URLs (for the contract consistency test).
 * MUST match ALL_SERVICE_URLS in shared/contracts/urls.py.
 */
export const ALL_SERVICE_URLS = [
  URL_KG_STATS,
  URL_KG_EXPLORE,
  URL_PREDICT,
  URL_TOP_K,
  URL_RANK,
  URL_RANK_BY_DRUG,
  URL_VALIDATE,
  URL_HEALTH,
] as const;

// ============================================================================
// DEFAULT SERVICE PORTS — MUST match shared/contracts/urls.py SERVICE_PORTS
// ============================================================================

export const SERVICE_PORTS = {
  phase1_dataset: 8000,
  phase2_kg: 8001,
  phase3_gt: 8002,
  phase4_rl: 8003,
  airflow_webserver: 8080,
  mlflow_tracking: 5000,
  neo4j_bolt: 7687,
  neo4j_http: 7474,
  postgres: 5432,
  frontend: 3000,
} as const;

export type ServiceName = keyof typeof SERVICE_PORTS;

// ============================================================================
// AUTO-GENERATED OPENAPI TYPES BELOW
// ============================================================================
// Everything from this point down is regenerated by
// ``frontend/scripts/generate_api_contracts.py``. Do not edit by hand —
// your changes will be overwritten on the next regeneration.

/* eslint-disable */
// @ts-nocheck — generated file; type errors here indicate an upstream
//               OpenAPI schema issue, not a code issue.


export interface paths {
  "/cypher": {
    post: {
    /** Operation ID: kg_cypher_cypher_post */
    /** Kg Cypher */
    requestBody: components["schemas"]["CypherBody"];
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
      422: { content: { "application/json": { schema: components["schemas"]["HTTPValidationError"] } } };
    };
    };
  };
  "/datasets": {
    get: {
    /** Operation ID: datasets_datasets_get */
    /** Datasets */
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
    };
    };
  };
  "/datasets/validated_hypotheses": {
    post: {
    /** Operation ID: create_validated_hypothesis_datasets_validated_hypotheses_post */
    /** Create Validated Hypothesis */
    requestBody: components["schemas"]["ValidatedHypothesisRequest"];
    responses: {
      201: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
      422: { content: { "application/json": { schema: components["schemas"]["HTTPValidationError"] } } };
    };
    };
  };
  "/datasets/{drug}/mechanism": {
    get: {
    /** Operation ID: drug_mechanism_datasets__drug__mechanism_get */
    /** Drug Mechanism */
    parameters: {
      drug: string;
    };
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
      422: { content: { "application/json": { schema: components["schemas"]["HTTPValidationError"] } } };
    };
    };
  };
  "/health": {
    get: {
    /** Operation ID: health_health_get */
    /** Health */
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
    };
    };
  };
  "/kg/explore": {
    get: {
    /** Operation ID: kg_explore_kg_explore_get */
    /** Kg Explore */
    parameters: {
      drug?: string | null;
      disease?: string | null;
      limit?: number;
    };
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
      422: { content: { "application/json": { schema: components["schemas"]["HTTPValidationError"] } } };
    };
    };
  };
  "/kg/stats": {
    get: {
    /** Operation ID: kg_stats_kg_stats_get */
    /** Kg Stats */
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
    };
    };
  };
  "/predict": {
    post: {
    /** Operation ID: phase3_gt_predict */
    /** phase3_gt POST /predict (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
    };
  };
  "/predictions": {
    get: {
    /** Operation ID: phase3_gt_get_predictions */
    /** phase3_gt GET /predictions (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
    };
  };
  "/query": {
    post: {
    /** Operation ID: kg_query_query_post */
    /** Kg Query */
    requestBody: components["schemas"]["QueryBody"];
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
      422: { content: { "application/json": { schema: components["schemas"]["HTTPValidationError"] } } };
    };
    };
  };
  "/rank": {
    get: {
    /** Operation ID: phase4_rl_rank_get */
    /** phase4_rl GET /rank (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
    };
    post: {
    /** Operation ID: phase4_rl_rank_post */
    /** phase4_rl POST /rank (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
    };
  };
  "/rank/{drug}": {
    get: {
    /** Operation ID: phase4_rl_rank_by_drug */
    /** phase4_rl GET /rank/{drug} (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
    };
  };
  "/stats": {
    get: {
    /** Operation ID: stats_stats_get */
    /** Stats */
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
    };
    };
  };
  "/top-k": {
    get: {
    /** Operation ID: phase3_gt_top_k */
    /** phase3_gt GET /top-k (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
    };
  };
  "/validate": {
    post: {
    /** Operation ID: phase4_rl_validate */
    /** phase4_rl POST /validate (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
    };
  };
}



export interface components {
  schemas: {
    CypherBody: {
    cypher: string;
    params?: {
    [key: string]: unknown;
  } | null;
  };
    HTTPValidationError: {
    detail?: Array<components["schemas"]["ValidationError"]>;
  };
    QueryBody: {
    disease?: string | null;
    drug?: string | null;
    limit?: number;
  };
    ValidatedHypothesisRequest: {
    disease: string;
    drug: string;
    notes?: string | null;
    original_gt_score?: number | null;
    original_rl_rank?: number | null;
    outcome: string;
    validated_at: string;
    validated_by?: string | null;
    validation_study_id?: string | null;
    writeback_version?: string | null;
  };
    ValidationError: {
    loc: Array<string | number>;
    msg: string;
    type: string;
  };
  };
}



export interface operations {
  kg_cypher_cypher_post: {
    /** Operation ID: kg_cypher_cypher_post */
    /** Kg Cypher */
    requestBody: components["schemas"]["CypherBody"];
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
      422: { content: { "application/json": { schema: components["schemas"]["HTTPValidationError"] } } };
    };
  };
  datasets_datasets_get: {
    /** Operation ID: datasets_datasets_get */
    /** Datasets */
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
    };
  };
  create_validated_hypothesis_datasets_validated_hypotheses_post: {
    /** Operation ID: create_validated_hypothesis_datasets_validated_hypotheses_post */
    /** Create Validated Hypothesis */
    requestBody: components["schemas"]["ValidatedHypothesisRequest"];
    responses: {
      201: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
      422: { content: { "application/json": { schema: components["schemas"]["HTTPValidationError"] } } };
    };
  };
  drug_mechanism_datasets__drug__mechanism_get: {
    /** Operation ID: drug_mechanism_datasets__drug__mechanism_get */
    /** Drug Mechanism */
    parameters: {
      drug: string;
    };
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
      422: { content: { "application/json": { schema: components["schemas"]["HTTPValidationError"] } } };
    };
  };
  health_health_get: {
    /** Operation ID: health_health_get */
    /** Health */
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
    };
  };
  kg_explore_kg_explore_get: {
    /** Operation ID: kg_explore_kg_explore_get */
    /** Kg Explore */
    parameters: {
      drug?: string | null;
      disease?: string | null;
      limit?: number;
    };
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
      422: { content: { "application/json": { schema: components["schemas"]["HTTPValidationError"] } } };
    };
  };
  kg_stats_kg_stats_get: {
    /** Operation ID: kg_stats_kg_stats_get */
    /** Kg Stats */
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
    };
  };
  phase3_gt_predict: {
    /** Operation ID: phase3_gt_predict */
    /** phase3_gt POST /predict (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
  };
  phase3_gt_get_predictions: {
    /** Operation ID: phase3_gt_get_predictions */
    /** phase3_gt GET /predictions (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
  };
  kg_query_query_post: {
    /** Operation ID: kg_query_query_post */
    /** Kg Query */
    requestBody: components["schemas"]["QueryBody"];
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
      422: { content: { "application/json": { schema: components["schemas"]["HTTPValidationError"] } } };
    };
  };
  phase4_rl_rank_get: {
    /** Operation ID: phase4_rl_rank_get */
    /** phase4_rl GET /rank (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
  };
  phase4_rl_rank_post: {
    /** Operation ID: phase4_rl_rank_post */
    /** phase4_rl POST /rank (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
  };
  phase4_rl_rank_by_drug: {
    /** Operation ID: phase4_rl_rank_by_drug */
    /** phase4_rl GET /rank/{drug} (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
  };
  stats_stats_get: {
    /** Operation ID: stats_stats_get */
    /** Stats */
    responses: {
      200: { content: { "application/json": { schema: {
    [key: string]: unknown;
  } } } };
    };
  };
  phase3_gt_top_k: {
    /** Operation ID: phase3_gt_top_k */
    /** phase3_gt GET /top-k (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
  };
  phase4_rl_validate: {
    /** Operation ID: phase4_rl_validate */
    /** phase4_rl POST /validate (AST-extracted) */
    responses: {
      200: { content: { "application/json": { schema: Record<string, never> } } };
    };
  };
}


// ────────────────────────────────────────────────────────────────────
// Referenced schema names (debugging aid — not used at runtime)
// ────────────────────────────────────────────────────────────────────
// CypherBody, HTTPValidationError, QueryBody, ValidatedHypothesisRequest, ValidationError
