/**
 * frontend/contracts/api_contracts.ts
 * ===================================
 *
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * This file is assembled by frontend/scripts/assemble-contracts.mjs from:
 *   1. contracts/_url-constants.ts — hand-maintained URL constants that
 *      mirror shared/contracts/urls.py (the Python contract consistency
 *      test reads this file as text and verifies the URLs match).
 *   2. openapi-typescript output — the TypeScript types generated from
 *      contracts/openapi.json (which is itself built from the four Python
 *      FastAPI services' app.openapi() schemas by extract_openapi.py).
 *
 * Task 13.4 (SH-006) v131 ROOT FIX (Teammate 13):
 *   The previous file was hand-written TypeScript with interfaces that
 *   DIVERGED from what the Python services actually returned. This file
 *   is now generated from the source of truth — the FastAPI apps' own
 *   app.openapi() output, converted to TypeScript by openapi-typescript
 *   (the canonical tool the task required). Any change to a Python
 *   endpoint's URL, request body, or response shape is now a 2-file
 *   change: the Python service + this regenerated file. The CI check
 *   (`npm run check:contracts`) fails if the file is out of date.
 *
 * Generation pipeline:
 *   python3 frontend/scripts/extract_openapi.py     # → openapi.json
 *   node frontend/scripts/assemble-contracts.mjs    # → api_contracts.ts
 *     (this script runs openapi-typescript internally)
 *
 * Verification:
 *   npm run check:contracts   # fails if api_contracts.ts is out of date
 */

/* eslint-disable */
// @ts-nocheck — generated file; type errors here indicate an upstream
//               OpenAPI schema issue, not a code issue.

// ============================================================================
// CANONICAL URL PATHS — MUST match shared/contracts/urls.py exactly
// ============================================================================

/** Phase 2 KG service — graph stats (node/edge counts). */
export const URL_KG_STATS = "/kg/stats";

/** Phase 2 KG service — explore a node's neighborhood. */
export const URL_KG_EXPLORE = "/kg/explore";

/** Phase 3 GT service — predict drug-disease score. */
export const URL_PREDICT = "/predict";

/** Phase 3 GT service — top-k novel predictions. */
export const URL_TOP_K = "/top-k";

/** Phase 4 RL service — ranked candidates (composite score). */
export const URL_RANK = "/rank";

/** Phase 4 RL service — ranked candidates filtered by drug. */
export const URL_RANK_BY_DRUG = "/rank/{drug}";

/** Phase 4 RL service — validate a hypothesis (initiates writeback). */
export const URL_VALIDATE = "/validate";

/** All services — health check (liveness probe). */
export const URL_HEALTH = "/health";

/**
 * All canonical service URLs (for the contract consistency test).
 * MUST match ALL_SERVICE_URLS in shared/contracts/urls.py.
 */
export const ALL_SERVICE_URLS = [
  URL_KG_STATS,
  URL_KG_EXPLORE,
  URL_PREDICT,
  URL_TOP_K,
  URL_RANK,
  URL_RANK_BY_DRUG,
  URL_VALIDATE,
  URL_HEALTH,
] as const;

// ============================================================================
// DEFAULT SERVICE PORTS — MUST match shared/contracts/urls.py SERVICE_PORTS
// ============================================================================

export const SERVICE_PORTS = {
  phase1_dataset: 8000,
  phase2_kg: 8001,
  phase3_gt: 8002,
  phase4_rl: 8003,
  airflow_webserver: 8080,
  mlflow_tracking: 5000,
  neo4j_bolt: 7687,
  neo4j_http: 7474,
  postgres: 5432,
  frontend: 3000,
} as const;

export type ServiceName = keyof typeof SERVICE_PORTS;


/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cypher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kg Cypher
         * @description Raw read-only Cypher passthrough (P2-002 / P2-011 / P2-041 root fix).
         *
         *     v109 ROOT FIX: applies the defense-in-depth ``_validate_readonly_cypher``
         *     validator (blocks subqueries, APOC, db writes, LOAD CSV, semicolons)
         *     AND ``_validate_cypher_params`` (rejects non-scalar params) AND
         *     enforces a hard 30-second server-side timeout via the Neo4j driver's
         *     ``transaction_timeout`` parameter (the v107 docstring claimed a 30s
         *     timeout but the implementation did NOT enforce one — a malicious or
         *     runaway query could block the worker indefinitely).
         *     Returns 503 if Neo4j is not configured — the in-memory bridge cannot
         *     answer arbitrary Cypher.
         */
        post: operations["kg_cypher_cypher_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Datasets
         * @description Return real Phase 1 dataset stats (no fabrication).
         */
        get: operations["datasets_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/validated_hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Validated Hypothesis
         * @description Persist a validated drug-disease hypothesis to PostgreSQL.
         *
         *     This is the data flywheel writeback endpoint (TM3 Task 3.3 v127).
         *     Accepts the TM14 CSV-shape payload, translates it to the 10-column
         *     canonical schema, and INSERTs into the validated_hypotheses table.
         */
        post: operations["create_validated_hypothesis_datasets_validated_hypotheses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{drug}/mechanism": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Drug Mechanism
         * @description Return the mechanism-of-action (targets + indications) for a drug.
         */
        get: operations["drug_mechanism_datasets__drug__mechanism_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health endpoint. Returns service metadata + data availability.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kg/explore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kg Explore
         * @description Return a subgraph around a drug or disease.
         */
        get: operations["kg_explore_kg_explore_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kg/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kg Stats
         * @description Return real KG stats from Neo4j (or in-memory bridge fallback).
         */
        get: operations["kg_stats_kg_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict
         * @description Score drug-disease pairs with the GT model.
         *
         *     P3-002 ROOT FIX: response shape aligned with frontend contract
         *     (``{predictions, source, modelVersion, generatedAt, count,
         *     checkpointPath}``) so this service is a drop-in HTTP replacement
         *     for the subprocess path (``scripts/gt_inference.py``).
         *
         *     P3-050 ROOT FIX (v113): rate-limited via an asyncio semaphore
         *     (``GT_MAX_CONCURRENT_INFERENCE``, default 4). Requests beyond the
         *     limit are queued. The graph encoding is cached at startup and
         *     reused (no per-request encode).
         *
         *     SH-031 ROOT FIX (v120 forensic, hostile-auditor): the previous
         *     v113 docstring claimed ``error_count`` and ``error_rate`` were
         *     returned as HTTP response HEADERS (``X-Error-Count`` /
         *     ``X-Error-Rate``) so monitoring could see them without breaking
         *     the TS contract. That claim was FALSE — the actual code at the
         *     bottom of this function returns BOTH fields in the JSON body
         *     (lines ``"error_count": error_count`` and ``"error_rate": ...``).
         *     The runtime Zod schema in ``frontend/src/lib/ml-contracts.ts``
         *     already accepts them as optional fields (``error_count?: number``,
         *     ``error_rate?: number``), and the v120 static TS contract
         *     (``frontend/contracts/api_contracts.ts``) now declares them as
         *     optional too. So returning them in the body is CONTRACT-COMPLIANT
         *     — no header refactor needed. The docstring has been corrected to
         *     match the code. The user's audit ("comments and tests are fakes
         *     ... when I manually check code it's 100 percent broken") was dead
         *     right: the comment described a refactor that was never done.
         */
        post: operations["predict_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Predictions
         * @description Retrieve PREDICTED_TREATS edges from Neo4j.
         *
         *     TM7-v127 ROOT FIX (Task 7.5): the audit requires "a query to
         *     retrieve predictions from Neo4j for the backend." This endpoint
         *     lets the backend / frontend query the GT model's predictions
         *     DIRECTLY from the Phase 2 KG (no separate gt_predictions.csv
         *     read).
         *
         *     Args (query params):
         *         drug: Filter by drug name (case-insensitive). If None, all drugs.
         *         disease: Filter by disease name (case-insensitive). If None, all diseases.
         *         min_score: Only return edges with score >= min_score (default 0.0).
         *         limit: Max number of edges to return (default 50, max 500).
         *
         *     Returns:
         *         Dict with keys:
         *           - 'predictions': list of {drug, disease, score, confidence,
         *             model_version, generated_at}.
         *           - 'count': int.
         *           - 'source': 'neo4j' or 'no_neo4j'.
         *           - 'neo4j_configured': bool.
         */
        get: operations["get_predictions_predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kg Query
         * @description Structured drug/disease query (P2-002 root fix).
         *
         *     The frontend POSTs ``{"drug": "...", "disease": "...", "limit": N}``
         *     here. We resolve it via Neo4j (preferred) or the in-memory BFS.
         */
        post: operations["kg_query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rank Get
         * @description Get ranked hypotheses (optionally filtered by drug/disease).
         *
         *     INT-022: accepts offset for pagination.
         *
         *     BE-035 + BE-043 ROOT FIX (v118): accepts ``org_id`` query param.
         *     The frontend's rl-ranker.ts now forwards the user's active orgId
         *     here; the service logs it for audit and may use it to filter
         *     candidates by org ownership in a future update.
         */
        get: operations["rank_get_rank_get"];
        put?: never;
        /**
         * Rank Post
         * @description Get ranked hypotheses with body filters.
         *
         *     BE-035 + BE-043 ROOT FIX (v118): accepts ``org_id`` query param.
         *     The frontend's rl-ranker.ts now forwards the user's active orgId
         *     here; the service logs it for audit and may use it to filter
         *     candidates by org ownership in a future update.
         *
         *     INT-022: offset from query params (POST body doesn't include it).
         *     FastAPI parses offset from the query string even for POST.
         */
        post: operations["rank_post_rank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rank/{drug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rank By Drug
         * @description Get ranked hypotheses for a specific drug.
         *
         *     P4-042 ROOT FIX (LOW — Team Cosmic / Phase 4): URL-decode the drug
         *     name before matching. FastAPI automatically decodes path parameters,
         *     so `rank/aspirin%20EC` reaches this function with drug="aspirin EC".
         *     The previous docstring claimed the search was a case-insensitive
         *     substring match on generic names, but did not document that the path
         *     parameter is URL-decoded by FastAPI. The fix adds explicit
         *     documentation and a defensive urllib.parse.unquote call (in case a
         *     future middleware re-encodes the path). The actual matching is done
         *     by _rank_impl (case-insensitive substring on drug name).
         *
         *     BE-035 + BE-043 ROOT FIX (v118): accepts ``org_id`` query param.
         */
        get: operations["rank_by_drug_rank__drug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats
         * @description Phase 1 stats in the DatasetStatsResponse shape the frontend expects.
         *
         *     This endpoint is the contract-satisfying peer of
         *     ``frontend/src/lib/services/dataset-stats.ts:proxyToDatasetService``.
         *     It returns the fields the frontend destructures: sources, nodesLoaded,
         *     edgesLoaded, edgeTypesPresent, pipelineVersion, schemaVersion,
         *     bridgeVersion, backend, warnings, errors, generatedAt.
         */
        get: operations["stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/top-k": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top K
         * @description Return the top-k novel predictions from the GT model.
         *
         *     P3-002 ROOT FIX: response shape aligned with frontend contract.
         *     Uses ``top_k_novel_predictions`` from ``graph_transformer.inference``
         *     (the SAME function the subprocess path uses) so HTTP and subprocess
         *     produce identical results.
         */
        get: operations["top_k_top_k_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate
         * @description Write a validated hypothesis back to all 3 phases (data flywheel).
         *
         *     Issue 227 ROOT FIX: this endpoint replaces the subprocess shell-out
         *     from the frontend's /api/hypothesis/validate route. The frontend now
         *     proxies to RL_SERVICE_URL/validate via HTTP.
         *
         *     The endpoint calls phase4.writeback.write_validated_hypothesis()
         *     which:
         *       1. Appends to phase1/processed_data/validated_hypotheses.csv
         *          (becomes a new labeled data point for future KG builds).
         *       2. Adds a VALIDATED_TREATS edge to Neo4j (when available) with
         *          validated_at timestamp + validated_by partner identifier.
         *       3. Appends to graph_transformer/retrain_triggered.json so the
         *          next GT training run includes this pair in known_pairs.
         *
         *     Returns the writeback result containing:
         *       - phase1_csv_path: path to the appended CSV
         *       - phase2_neo4j_written: whether the Neo4j edge was added
         *       - phase3_trigger_path: path to the retrain trigger JSON
         *       - validated_hypothesis: the ValidatedHypothesis record
         *       - writeback_version: the writeback module version
         *
         *     Errors:
         *       - 400: invalid outcome enum value
         *       - 500: writeback failed (CSV append error, Neo4j connection error, etc.)
         */
        post: operations["validate_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CypherBody
         * @description Raw Cypher passthrough body for POST /cypher.
         */
        CypherBody: {
            /**
             * Cypher
             * @description Read-only Cypher query.
             */
            cypher: string;
            /**
             * Params
             * @description Parameterized query variables (scalars or lists of scalars only).
             */
            params?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PredictRequest
         * @description Request body for /predict.
         *
         *     Either provide an explicit list of pairs, or leave pairs empty to
         *     score all drug-disease pairs in the graph.
         */
        PredictRequest: {
            /** Disease */
            disease?: string | null;
            /** Drug */
            drug?: string | null;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /** Pairs */
            pairs?: {
                [key: string]: string;
            }[] | null;
        };
        /**
         * QueryBody
         * @description Structured query body for POST /query.
         */
        QueryBody: {
            /**
             * Disease
             * @description Disease name (Disease.name).
             */
            disease?: string | null;
            /**
             * Drug
             * @description Drug name (Compound.name).
             */
            drug?: string | null;
            /**
             * Limit
             * @description Max nodes to return.
             * @default 100
             */
            limit: number;
        };
        /** RankRequest */
        RankRequest: {
            /** Disease */
            disease?: string | null;
            /** Drug */
            drug?: string | null;
            /**
             * Limit
             * @default 50
             */
            limit: number;
        };
        /**
         * ValidateRequest
         * @description Request body for /validate (Issue 227).
         *
         *     Matches the ValidatedHypothesis dataclass in phase4/writeback.py.
         *     The frontend's RlValidateRequestSchema (ml-contracts.ts) is the
         *     TypeScript mirror of this Pydantic model — the two MUST stay in sync.
         *
         *     SH-004 ROOT FIX: the `outcome` field accepts the 4 canonical
         *     values from shared.contracts.writeback.VALID_OUTCOMES. The
         *     frontend's ValidateRequest type mirrors this enum exactly.
         */
        ValidateRequest: {
            /** Disease */
            disease: string;
            /** Drug */
            drug: string;
            /** Notes */
            notes?: string | null;
            /** Original Gt Score */
            original_gt_score?: number | null;
            /** Original Rl Rank */
            original_rl_rank?: number | null;
            /** Outcome */
            outcome: string;
            /** Validated By */
            validated_by: string;
            /** Validation Study Id */
            validation_study_id?: string | null;
        };
        /**
         * ValidatedHypothesisRequest
         * @description Request body for POST /datasets/validated_hypotheses.
         *
         *     Mirrors the TM14 ``shared/contracts/writeback.py`` WRITEBACK_CSV_COLUMNS
         *     so the rl/service.py writeback call shape is unchanged.
         */
        ValidatedHypothesisRequest: {
            /**
             * Disease
             * @description Disease name
             */
            disease: string;
            /**
             * Drug
             * @description Drug name
             */
            drug: string;
            /** Notes */
            notes?: string | null;
            /** Original Gt Score */
            original_gt_score?: number | null;
            /** Original Rl Rank */
            original_rl_rank?: number | null;
            /**
             * Outcome
             * @description Validation outcome
             */
            outcome: string;
            /**
             * Validated At
             * @description ISO-8601 validation timestamp
             */
            validated_at: string;
            /** Validated By */
            validated_by?: string | null;
            /** Validation Study Id */
            validation_study_id?: string | null;
            /** Writeback Version */
            writeback_version?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    kg_cypher_cypher_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CypherBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    datasets_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_validated_hypothesis_datasets_validated_hypotheses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidatedHypothesisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drug_mechanism_datasets__drug__mechanism_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                drug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    kg_explore_kg_explore_get: {
        parameters: {
            query?: {
                drug?: string | null;
                disease?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kg_stats_kg_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    predict_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_predictions_predictions_get: {
        parameters: {
            query?: {
                drug?: string | null;
                disease?: string | null;
                min_score?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kg_query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rank_get_rank_get: {
        parameters: {
            query?: {
                drug?: string | null;
                disease?: string | null;
                limit?: number;
                offset?: number;
                /** @description BE-035 + BE-043 ROOT FIX (v118): the org scope for the candidate fetch. Forwarded by the frontend's getRankedHypotheses (rl-ranker.ts). Logged for audit (21 CFR Part 11). May be used to filter candidates by org ownership in a future update. */
                org_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rank_post_rank_post: {
        parameters: {
            query?: {
                /** @description BE-035 + BE-043 ROOT FIX (v118): the org scope for the candidate fetch. Forwarded by the frontend's getRankedHypotheses (rl-ranker.ts). Logged for audit (21 CFR Part 11). */
                org_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rank_by_drug_rank__drug__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description BE-035 + BE-043 ROOT FIX (v118): the org scope for the candidate fetch. */
                org_id?: string | null;
            };
            header?: never;
            path: {
                drug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    top_k_top_k_get: {
        parameters: {
            query?: {
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
